### ISSUE TITLE
Search by label

### ISSUE THREAD

**Issue by modernmediagrp** [Dniel97/orpheusdl-beatport#1]
Any way to search by labels?

**Comment by Dniel97** [comment]
Labels or Publisher are currently not supported by OepheusDL at all, therefore no downloading and searching will work.

**Comment by Romchess1985** [comment]
Hi! already stopped downloading some tracks. It says it's about python 310 and mutagen.

![image](https://github.com/Dniel97/orpheusdl-beatport/assets/54895142/955ab2a7-a416-498e-85b7-a6b3345fa7af)

**Comment by yarrm80s** [comment]
@Romchess1985 Also, why are you using OrpheusDL through mingw...?
