### ISSUE TITLE
Downloader Stops working with multiple links under certain scenerios.

### ISSUE THREAD

**Issue by SquashingBugs** [Dniel97/orpheusdl-beatport#10]
Scenerio 1: Invalid Flac File name
![Bug](https://github.com/user-attachments/assets/83046b34-e3d5-43a1-bed4-bd4bb4f7efee)
Applies to only 1 file in the playlist. When attempting to download a 2nd time, the problematic file is skipped and the remaining of the playlist downloads like usual. Attempting to download that same file as an individual track yields the same error.
https://www.beatport.com/track/pietres-dance/19516517
https://www.beatport.com/chart/best-new-afro-house-october-2024/829133

Scenerio 2: Unsupported operand Types(s)
![playlist](https://github.com/user-attachments/assets/22e2ef26-45a5-461a-8cf7-e2f9d333556d)
![trance main floor](https://github.com/user-attachments/assets/4a493e80-5656-48e1-8b61-ad5ee6765fa3)
This one I can't really explain too much, but for some reason, these playlists do not want to download at all. A few examples:
https://www.beatport.com/chart/best-new-hype-trance-main-floor-sep-2024/826510
https://www.beatport.com/playlists/share/4154289 (user-made version of same playlist as 1st link, playlist in the 2nd screenshot)
https://www.beatport.com/chart/weekend-picks-house-2024-week-34/825076
https://www.beatport.com/chart/best-new-house-august/823368 
https://www.beatport.com/chart/best-new-bass-club-august-2024/823330
https://www.beatport.com/chart/best-new-140-deep-dubstep-august-2024/823329
https://www.beatport.com/chart/best-new-deep-house-august-2024/823264 (playlist in the 1st screenshot)
https://www.beatport.com/chart/best-new-dance-august-2024/823223
I even tried to create a playlist, from the playlist and it still failed to download.

What I would like to see instead is either for these tracks and playlist types to download properly, or if this is not possible, have that one track skipped the same way non-streamable and geo-restricted tracks are skipped, and have the playlist skipped so the others can download, and not have to re-queue everything. Maybe having a log that displays every failed track / playlist.

Computer name is blocked out for Privacy Reasons. Using macOS 12 on Terminal.

**Comment by cheesetosti** [comment]
Seems like the downloaded .flac file, when opened as a text file, says: <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
