### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by beats2588** [Dniel97/orpheusdl-beatport#13]
Did it just stopped working? Im getting error:

ConnectionError: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden

**Comment by JorickDJ** [comment]
Changing the user-agent in **beatport_api.py** to:
`
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
`
fixed this issue for me. Not sure if this is a real fix.

**Comment by beats2588** [comment]
Can confirm, working with editing user-agent, thank you man!

**Comment by huiskesmartijn** [comment]
> Changing the user-agent header value in **beatport_api.py** to: `'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',` fixed this issue for me. Not sure if this is a real fix.

While this did do the job, I am getting the following message still:
" Beatport: Account does not have an active "Link" subscription"

While I do have a subscription

**Comment by qyraai** [comment]
> > Changing the user-agent header value in **beatport_api.py** to: `'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',` fixed this issue for me. Not sure if this is a real fix.
> 
> While this did do the job, I am getting the following message still: " Beatport: Account does not have an active "Link" subscription"
> 
> While I do have a subscription

That happens with me also

**Comment by maydans100** [comment]
same here.

**Comment by huiskesmartijn** [comment]
Seems like beatport changed a bit the way in which the login is done. Looked a bit a the requests sent to the API when logging in, and I think its relatively easy to fix. I might have some time tomorrow.

**Comment by MadeInMachines** [comment]
I have some problem too - was working perfectly before. ConnectionError: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden

**Comment by JorickDJ** [comment]
> Seems like beatport changed a bit the way in which the login is done. Looked a bit a the requests sent to the API when logging in, and I think its relatively easy to fix. I might have some time tomorrow.

If you have a fix, share it! Probably changed the model or something.

**Comment by maydans100** [comment]
> Changing the user-agent header value in **beatport_api.py** to: `'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',` fixed this issue for me. Not sure if this is a real fix.

have you come up with any new fix?

**Comment by huiskesmartijn** [comment]
> @JorickDJ can you try my fix? [dracarys69@b912b83](https://github.com/dracarys69/orpheusdl-beatport/commit/b912b837180913095be8f32caecd6f1328707eb9)

I don’t see any changes with respect to the original code in your commit?

**Comment by cheesetosti** [comment]
Commenting out the client_secret line worked for me too, thanks!

**Comment by MadeInMachines** [comment]
I can't get either of these fixes to work for me - 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36', - Said I didn't have a valid subscription. I'm not sure i'm doing the client_secret line fix right but it didn't seem to work either.

**Comment by MadeInMachines** [comment]
Changing the user agent header and client_secret Worked for me

**Comment by exomarketer** [comment]
> Changing the user-agent header value in **beatport_api.py** to: `'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',` fixed this issue for me. Not sure if this is a real fix.

I applied these changes to the header, and now it shows me another error that I don't have an active membership, but the truth is that I do have an active membership.

**This is the new error:**

Traceback (most recent call last):
  File "/Users/smart/Desktop/Python/OrpheusDL/orpheus.py", line 225, in <module>
    main()
    ~~~~^^
  File "/Users/smart/Desktop/Python/OrpheusDL/orpheus.py", line 180, in main
    module = orpheus.load_module(service_name)
  File "/Users/smart/Desktop/Python/OrpheusDL/orpheus/core.py", line 210, in load_module
    loaded_module = class_(module_controller)
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/interface.py", line 54, in __init__
    self.login(module_controller.module_settings['username'], module_controller.module_settings['password'])
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/interface.py", line 90, in login
    self.valid_account()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/smart/Desktop/Python/OrpheusDL/modules/beatport/interface.py", line 97, in valid_account
    raise self.exception('Beatport: Account does not have an active "Link" subscription')
orpheus.core.Orpheus.load_module.<locals>.ModuleError: beatport --> Beatport: Account does not have an active "Link" subscription
