### ISSUE TITLE
Grab catalognumber & totaltracks

### ISSUE THREAD

**Issue by cheesetosti** [Dniel97/orpheusdl-beatport#16]
Any possibility to also embed the catalog number and the release's total tracks into the downloaded files? This would help with automating my music organising workflow a lot!

**Comment by cheesetosti** [comment]
Totaltracks seems to be fixed with the develop branch

**Comment by Dniel97** [comment]
What do you mean by catalog number exactly?

**Comment by cheesetosti** [comment]
The "Catalog" code, stated underneath the "Label" and "Release Date". E.g. for this release, the catalog number is "AL097":
https://www.beatport.com/release/along-came-polly-konstantin-sibold-zac-carmee-remix/4687021

This catalog number is used by record labels to give their releases a number in their releases collection

**Comment by qyraai** [comment]
> What exactly do you mean by catalog number?

Hello Master!!
It will also be great to see the Release Catalog in the tags.

I hope I can be an easy modification.
