### ISSUE TITLE
.flac" is not a valid FLAC file

### ISSUE THREAD

**Issue by qyraai** [Dniel97/orpheusdl-beatport#19]
Hello, @Dniel97 
    
    I am getting this error on Flac, plus other files...
       
'raise FLACNoHeaderError(
mutagen.flac.FLACNoHeaderError: "../../dl/The Cult Remixed/1. Life Worth Living (Deadbeat's Keep It Trippy Remix).flac" is not a valid FLAC file'

**Comment by MadeInMachines** [comment]
I'm getting the same on every file

**Comment by cheesetosti** [comment]
HAHAHA WHAT?! I dowloaded this one and got the same error - the output flac is literally a part of a Rickroll, WTF? https://www.beatport.com/track/life-worth-living/19609422

**Comment by cheesetosti** [comment]
Temporary solution: comment out  `self.client_id = "5yfTsQ6B31nNXPsImGyeZiZ6oDzDiwG50E7FS92j"` inside beatport_api.py

**Comment by shoenko** [comment]
beatport probably restricted the use of the endpoint `/catalog/tracks/{track_id}/download` with the client id, lol

**Comment by MadeInMachines** [comment]
> HAHAHA WHAT?! I dowloaded this one and got the same error - the output flac is literally a part of a Rickroll, WTF? https://www.beatport.com/track/life-worth-living/19609422
> 
> thanks for the laugh Beatport IT!

So it is! Banger

**Comment by maydans100** [comment]
anyway to solve that?

**Comment by MadeInMachines** [comment]
> Please use the develop version and report if it has the same issue.

How do you get this version?

**Comment by JorickDJ** [comment]
> > Please use the develop version and report if it has the same issue.
> 
> Hi @Dniel97, Yes, I can confirm that. I have exact the same issue
> 
> FLACs are getting errors, downloads stops as ".flac' is not a valid FLAC file" The lower quality download fake files such as "Never Gonna Give You Up" by Rick Astley

It's not only FLAC's, Beatport returns a Rick Roll file for every track. I suspect they did something with the client_id.

**Comment by tyrex355** [comment]
Allah won't forgive beatport for rickrolling us

**Comment by MadeInMachines** [comment]
Still the same with the development version

**Comment by mass83** [comment]
> Все то же самое с версией разработки

Yes, the same thing

**Comment by mass83** [comment]
> Still the same with the development version

Yes, the same thing

**Comment by Jlianni** [comment]
Same issue here. I also using development version.
