### ISSUE TITLE
ConnectionError: {"detail":"CSRF Failed: Referer checking failed - no Referer."}

### ISSUE THREAD

**Issue by meowingtons0808** [Dniel97/orpheusdl-beatport#22]
Traceback (most recent call last):
  File "/Users/____/KKKK/orpheusdl/orpheus.py", line 224, in <module>
    main()
  File "/Users/____/KKKK/orpheusdl/orpheus.py", line 179, in main
    module = orpheus.load_module(service_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/____/KKKK/orpheusdl/orpheus/core.py", line 224, in load_module
    loaded_module.login(settings['email'] if 'email' in settings else settings['username'], settings['password'])
  File "/Users/____/KKKK/orpheusdl/modules/beatport/interface.py", line 78, in login
    login_data = self.session.auth(username, password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/____/KKKK/orpheusdl/modules/beatport/beatport_api.py", line 55, in auth
    raise ConnectionError(r.text)

how i can fix this?

**Comment by SquashingBugs** [comment]
Can confirm:
![temp](https://github.com/user-attachments/assets/967c84c8-65d7-4549-afb1-6960aafc95c2)

**Comment by meowingtons0808** [comment]
same bro

**Comment by tomtom2430** [comment]
I'm getting the same error, maybe beatport updated something on their system?

**Comment by Dniel97** [comment]
@tomtom2430, @meowingtons0808, @SquashingBugs Can you try the latest develop commit and tell me if that fixed it?

**Comment by tomtom2430** [comment]
> @tomtom2430, @meowingtons0808, @SquashingBugs Can you try the latest develop commit and tell me if that fixed it?

I'm sorry but it's still not working, I deleted everything and re-installed everything but it's still the same issue.
![Uploading Screanshot.png…]()

**Comment by meowingtons0808** [comment]
maybe beatport watching you
