### ISSUE TITLE
Support Playlists Downloads

### ISSUE THREAD

**Issue by qyraai** [Dniel97/orpheusdl-beatport#24]
Hello,
 is it possible to add a feature for playlist downloads?
 
 @Dniel97 How can I donate?
 
 Best Regards

**Comment by Dniel97** [comment]
That is already supported? Do you have an example link which doesn't work?

**Comment by qyraai** [comment]
> That is already supported? Do you have an example link which doesn't work?

Hi, I meant the playlists I have created. 

The error log is "AttributeError: 'NoneType' object has no attribute 'group'"

ref: link https://www.beatport.com/library/playlists/4346636

**Comment by cheesetosti** [comment]
Did you set the playlist to "Public"?

**Comment by qyraai** [comment]
Yes, it's set to "Public"

**Comment by JorickDJ** [comment]
You need to click on the link icon in share section to get the link to download a playlist. Copying the url doesn’t work.

![IMG_5498](https://github.com/user-attachments/assets/4a41ec8c-eabf-4688-a1f3-5fb67c90152f)

**Comment by qyraai** [comment]
> You need to click on the link icon in share section to get the link to download a playlist. Copying the url doesn’t work.
> 
> ![IMG_5498](https://private-user-images.githubusercontent.com/5736479/394200723-4a41ec8c-eabf-4688-a1f3-5fb67c90152f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTY0MjIsIm5iZiI6MTczMzg5NjEyMiwicGF0aCI6Ii81NzM2NDc5LzM5NDIwMDcyMy00YTQxZWM4Yy1lYWJmLTQ2ODgtYTFmMy01ZmI2N2M5MDE1MmYuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA1NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMzU4MjVjZDg1NzQwMjkwY2MyZDY2MzEzNGI2ZTY4ZTM2YTdhNzY4MTc3MmIyYTNiOWQwMTVlNjJmZWViMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hpYWZWuQPIyL9YhRkEQqG2xxOwzLO04FUdzOrW0poaQ)

@JorickDJ That makes sense!! 
Thank you
