### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Romchess1985** [Dniel97/orpheusdl-beatport#9]
Hi! got this email that they are planning to launch beatport streaming soon. They want to bring back lossy or add full lossless! 

Highest quality, lossless audio is waiting for you
We are delighted to announce that you can now mix our 12m+ electronic music catalog in crystal clear, lossless audio with our Beatport Streaming Professional plan.Highest quality lossless audio is available in most of our DJ integrations, with Traktor and rekordbox coming soon. Serato support for Windows is also on the way, with Mac support ready now. Resubscribe today to hear your favorite tracks like you've never heard them before.

**Comment by Dniel97** [comment]
Hey, 
already done, see a404c1e927527cc3089df9862e2a0ebda6cc55aa.
